services:
  galactus:
    build:
      context: .
    ports:
      - "3000:3000"
    # network_mode: host
    volumes:
    - .:/app  
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: galactus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
